import { test, expect } from '@playwright/test';

test('Code generated by "npx playwright codegen"', async ({ page }) => {
  await page.goto('https://www.bluewin.ch/de/index.html');
  await page.getByRole('button', { name: 'Akzeptieren' }).click();
  await expect(page.getByRole('link', { name: 'E-Mail' }).nth(1)).toBeVisible();
  await page.getByRole('link', { name: 'E-Mail' }).nth(1).click();
  await expect(page.getByTestId('page-title')).toContainText('Swisscom Login');
});